const PRODUCTS = [
    {
        id: "prod_001",
        name: "My Melody Pink Plush Backpack",
        description: "Adorable My Melody plush backpack in pink with bow detail and ribbon straps.",
        price: 15.00,
        weight: 6.0, 
        image: "assets/images/MyMelodyPinkBack.png",
        category: "sanrio",
        inStock: true,
    },
    {
        id: "prod_002",
        name: "My Melody White Plush Backpack",
        description: "Adorable My Melody plush backpack in white with pink bow detail and ribbon straps.",
        price: 15.00,
        weight: 6.0,
        image: "assets/images/mymelody-white-backpack.png",
        category: "sanrio",
        inStock: true,
    },
    {
        id: "prod_003",
        name: "Hello Kitty 3D Printed Keychain",
        description: "Custom 3D printed Hello Kitty face keychain with red bow. Handmade.",
        price: 2.00,
        weight: 3.0,
        image: "assets/images/HelloKitty3DChain.png",
        category: "sanrio",
        inStock: true,
    },
    {
        id: "prod_004",
        name: "Kuromi Pink Lighter",
        description: "Pink Kuromi character lighter with bead chain detail.",
        price: 15.00,
        weight: 8.0,
        image: "assets/images/KuromiPinkLighter.png",
        category: "sanrio",
        inStock: true,
    },
    {
        id: "prod_005",
        name: "Kuromi Purple Lighter",
        description: "Purple Kuromi character lighter with bead chain detail.",
        price: 15.00,
        weight: 8.0,
        image: "assets/images/KuromiPurpleLighter.png",
        category: "sanrio",
        inStock: true,
    },
    {
        id: "prod_006",
        name: "Pompom Plush Keychain",
        description: "Soft Pompom Purin plush keychain with bead chain clip.",
        price: 5.00,
        weight: 5.0,
        image: "assets/images/PompomPlushChain.png",
        category: "sanrio",
        inStock: true,
    },
    {
        id: "prod_007",
        name: "My Melody Plush Keychain",
        description: "Soft My Melody plush keychain with teal bow and bead chain clip.",
        price: 5.00,
        weight: 5.0,
        image: "assets/images/MyMelodyPlushChain.png",
        category: "sanrio",
        inStock: true,
    },
    {
        id: "prod_008",
        name: "Hello Kitty Plush Keychain",
        description: "Soft Hello Kitty plush keychain with red bow and bead chain clip.",
        price: 5.00,
        weight: 5.0,
        image: "assets/images/HelloKittyPlushChain.png",
        category: "sanrio",
        inStock: true,
    },
    {
        id: "prod_009",
        name: "Hello Kitty Necklace",
        description: "Silver Hello Kitty silhouette necklace with crystal detail.",
        price: 8.00,
        weight: 2.0,
        image: "assets/images/HelloKittyNecklace.png",
        category: "sanrio",
        inStock: true,
    },
    {
        id: "prod_010",
        name: "Princess Crown 2pc Ring Set",
        description: "Silver princess crown and chevron ring set with crystal accents. Set of 2.",
        price: 7.00,
        weight: 3.0,
        image: "assets/images/PrincessCrownRing2pcs.png",
        category: "sanrio",
        inStock: true,
    },
];

const PAYPAL_CLIENT_ID = "AVQ02ZqPTzoJQCTh7dh_-9T1OXYrTu09jQaJ868qwnD5jfqGchwarR1PaxWJhCyf-8RVme1A9lfgEKsp";

const TAX_CONFIG = {
    "AZ": 0.056,
    "DEFAULT": 0.00
};

const SOCIAL_LINKS = {
    instagram: "https://www.instagram.com/shopyuri.20/",
    instagram_backup: "https://www.instagram.com/shopyuri.20backup/",
    instagram_art: "https://www.instagram.com/yuris.paintings/",
    tiktok: "https://www.tiktok.com/@shopyuri.20",
    facebook: "https://www.facebook.com/profile.php?id=100084242085645",
};